---
title: "Death_by_state_peru"
author: "Emilio Sopprani"
date: "2024-10-09"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#Import the data set
fallecidos_covid <- read.csv("~/COVID-19 Analysis Peru/fallecidos_covid.csv", sep=";")
# Filtering our data to get rid of all the rubbish
filtered_data <- fallecidos_covid |> select(DEPARTAMENTO, SEXO) |> # Select only the variables we are going to use
  filter(DEPARTAMENTO != "MASCULINO") |> # There is a mislabeled state as "Masculino" So we are choosing all the entries but that one.
  drop_na() |> # Just in Case
  summarize(.by = c(DEPARTAMENTO, SEXO), n = n()) # we collapse all the Masculine and Femenine counts by departamento and include the number "n" of observations

#We are creating our contingency table
cont_table <- filtered_data |>
  pivot_wider(names_from = SEXO, values_from = n) |> #The sex needs to be separated into columns so it is pivoted wider.
  as.data.frame() #turned as a df

#Change the row names to each DEPARTAMENTO to get a nice Contingecy table

rownames(cont_table) <- cont_table$DEPARTAMENTO #Change the row names to the state instead of having a column with it

#change the names so all the non-spanish speaking peeps can understand
cont_table <- cont_table |> 
  mutate("male" = MASCULINO,
         "female" = FEMENINO)

#selecting the useful columns and transforming it as a matrix to put in chisq.test()

cont_table_matrix <- cont_table |>
  select(c(male,female)) |> 
  as.matrix()


#H0 = There is no difference in deaths by sex amongst each Peruvian state
#H1 = There is a difference in deaths by sex amongst each Peruvian state
#There is one group "LIMA METROPOLITANA" that has only 8 observations (4 male/4 female) but its fine bc we have 52 entries so no assumptions are violated :)
x2 <- chisq.test(cont_table_matrix)
print(x2$p.value)

```

