---
title: "Is there a super strong correlation between temperature and ice cream sales?"
author: "Emilio Sopprani, Grace 3Rico, Gonzalo Quintanilla, Mark Hegedus"
date: "2024-11-13"
output:
  html_document:
    code_folding: show
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(kableExtra)
library(stringi)
knitr::opts_chunk$set(echo = TRUE)
```

# - Helper function

```{r}
show_head <- function(df) {
  head(df) %>% # passing down only few lines from the df
    knitr::kable(format = "html") %>% # showing the lines in html format
    kable_styling(bootstrap_options = "striped", full_width = FALSE) %>% # little bit of style to avoid columns to be crowded
    kableExtra::scroll_box(width = "100%") # make it scrollable so the columns don't overflow the page
}
```


# - Import dataset

```{r}
sales <- read.csv("./ice_cream_sales_temperatures.csv")
show_head(sales)  # show head of the sales dataset
```

# - Visualize data

```{r}
# plot our dataset to get an intuition of what it looks like
sales %>%
  ggplot(mapping = aes(x = Temperature, y = Ice.Cream.Profits)) +
  geom_point()
```

# - Correlation

```{r}
r_squared <- cor(sales$Temperature, sales$Ice.Cream.Profits)  # calculate correlation coefficient

# plot dataset with correlation coefficient
sales %>% ggplot(mapping = aes(x = Temperature, y = Ice.Cream.Profits)) +
  geom_point() +
  annotate("text", x = Inf, y = Inf, label = paste0("R²: ", round(r_squared, 2)), hjust = 1.1, vjust = 1.1) +
  theme(legend.position = "none")

# calculate confidence interval of the correlation
cor_test <- cor.test(sales$Temperature, sales$Ice.Cream.Profits)
cor_test$conf.int
```
